select * from customer limit 20;

--what is the total revenue generated by male vs female customers
select gender,SUM(purchase_amount) as revenue
from customer
group by gender

--which customers used a discount but still spent more than the average purchase amount
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select AVG(purchase_amount) from customer)

--which top 5 products with the highest average review rating
select item_purchased,ROUND(AVG(review_rating::numeric),2) as "Average Review Rating" 
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--compare the average purchase amounts between standard and express shipping
select shipping_type, ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Do subscribed customers spend more? compare avg spend and total revenue between subs and non subs
select subscription_status, 
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--which 5 products have the highest percentage of purchases with discounts applied
select item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' Then 1 else 0 END)/Count(*),2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc 
limit 5;

--segment customers into NEW,RETURNING,LOYAL based on their total 
--num of previous purchases and show count of each segment
with customer_type as( 
select customer_id,previous_purchases, 
CASE
    WHEN previous_purchases=1 THEN 'NEW' 
	WHEN previous_purchases between 2 and 10 then 'Returning' 
	else 'Loyal' 
End AS customer_segment from customer ) 
select customer_segment,count(*) as "Number_of_Customers" 
from customer_type 
group by customer_segment;

--what are the top 3 most purchased products within each category
with item_counts as( 
select category, item_purchased, 
count(customer_id) as "total_orders", 
ROW_NUMBER() OVER(PARTITION BY category order by count(customer_id)DESC) as "item_rank" 
from customer 
group by category,item_purchased ) 

select item_rank,category,item_purchased,total_orders 
from item_counts where item_rank<=3;

--are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe
select subscription_status, count(customer_id) as repeat_buyers 
from customer
where previous_purchases>5 
group by subscription_status;

--what is the revenue contribution of each age group
select age_group, SUM(purchase_amount) as total_revenue 
from customer 
group by age_group 
order by total_revenue desc;



